import { expect, test } from "@playwright/test";

test("core preview traps focus and customization saves an owned version", async ({ page, request }) => {
  const signup = await request.post("/api/auth/signup", { data: { name: "Dashboard audit", email: `dashboard-${Date.now()}@example.test`, password: "speaking-pass" } });
  expect(signup.status()).toBe(201);
  const { token } = await signup.json();
  await page.addInitScript((value) => localStorage.setItem("quizstrike_token", value), token);
  await page.goto("/quiz-strike/teacher/speaking/core");
  await expect(page.getByRole("tab", { name: /My Speaking Tasks/ })).toBeVisible();
  await expect(page.getByRole("tab", { name: /Core Library 79/ })).toBeVisible();
  await expect(page.getByRole("tab", { name: /My Sets/ })).toBeVisible();
  await expect(page.locator(".speaking-collection-card")).toHaveCount(2);
  await expect(page.getByText("Ready-made speaking tasks for school and workplace English.", { exact: true })).toBeVisible();
  await expect(page.locator(".speaking-collection-card").filter({ hasText: "School English" })).toContainText("30");
  await expect(page.locator(".speaking-collection-card").filter({ hasText: "Workplace English" })).toContainText("49");
  await expect(page.getByText("No scenarios match", { exact: true })).toHaveCount(0);
  await page.locator(".speaking-collection-card").filter({ hasText: "Workplace English" }).click();
  await expect(page.locator(".speaking-category-card")).toHaveCount(6);
  await page.getByRole("button", { name: /Luxury Car Sales/ }).click();
  await expect(page.locator(".speaking-core-card")).toHaveCount(9);
  await page.getByLabel("Search scenarios", { exact: true }).fill("trade-in");
  await expect(page.locator(".speaking-core-card")).toHaveCount(1);
  await page.getByLabel("Search scenarios", { exact: true }).fill("");
  await page.getByRole("button", { name: "Core Library", exact: true }).click();
  await page.locator(".speaking-collection-card").filter({ hasText: "School English" }).click();
  await expect(page.locator(".speaking-category-card")).toHaveCount(8);
  await page.getByRole("button", { name: /Shopping & Services/ }).click();
  await expect(page.locator(".speaking-core-card")).toHaveCount(2);
  await page.getByLabel("Filter by communication skill").selectOption("Comparing");
  await expect(page.locator(".speaking-core-card")).toHaveCount(2);
  await page.getByRole("button", { name: "Clear filters" }).click();
  await page.getByLabel("Search scenarios", { exact: true }).fill("trade-in");
  await expect(page.locator(".speaking-core-card")).toHaveCount(1);
  await expect(page.locator(".speaking-core-card")).toContainText("Workplace English");
  await expect(page.locator(".speaking-core-card")).toContainText("Luxury Car Sales");
  await page.getByLabel("Search scenarios", { exact: true }).fill("allergy");
  await expect(page.locator(".speaking-core-card")).toContainText("Handling Dietary Questions");
  await page.getByLabel("Search scenarios", { exact: true }).fill("meeting");
  await expect(page.locator(".speaking-core-card").filter({ hasText: "Arranging a Meeting" })).toHaveCount(1);
  await page.getByLabel("Search scenarios", { exact: true }).fill("");
  for (const width of [1366, 768, 390]) {
    await page.setViewportSize({ width, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
  }
  await page.setViewportSize({ width: 1366, height: 844 });
  await page.getByLabel("Search scenarios", { exact: true }).fill("Buying Clothes");
  await expect(page.locator(".speaking-core-card")).toHaveCount(1);
  const trigger = page.getByRole("button", { name: "Preview", exact: true });
  await trigger.click();
  const dialog = page.getByRole("dialog");
  const close = dialog.getByRole("button", { name: "Close preview" });
  await expect(close).toBeFocused();
  await close.press("Shift+Tab");
  await expect(dialog.getByRole("button", { name: "Use as-is" })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(close).toBeFocused();
  await expect(dialog).toContainText("Assessment");
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  await page.getByRole("button", { name: "Customize", exact: true }).click();
  await expect(page.getByLabel("Task name", { exact: true })).toHaveValue("Buying Clothes");
  await page.locator("summary").filter({ hasText: "Advanced settings" }).click();
  await page.getByLabel("Additional focus or class content").fill("Notice polite requests and class vocabulary.");
  await page.getByRole("button", { name: "Create task", exact: true }).last().click();
  await expect(page).toHaveURL(/\/activity\/[^/]+$/);
  const id = new URL(page.url()).pathname.split("/").at(-1);
  const response = await request.get(`/api/speaking/activities/${id}`, { headers: { Authorization: `Bearer ${token}` } });
  const { activity } = await response.json();
  expect(activity.scenarioResources.builtIn).toBe(false);
  expect(activity.scenarioResources.teacherFocus).toBe("Notice polite requests and class vocabulary.");
  expect(activity.scenarioResources.sourceTemplateId).toBeTruthy();
  expect(activity.rubric.map((criterion: { id: string }) => criterion.id)).toEqual(["task_achievement", "interaction", "language_range_control", "communication_fluency"]);

  const setResponse = await request.post("/api/speaking/sets", { headers: { Authorization: `Bearer ${token}` }, data: { name: "Grade 2 Conversation", focus: "Pay particular attention to follow-up questions and clarification." } });
  expect(setResponse.status()).toBe(201);
  const { set } = await setResponse.json() as { set: { id: string; focus: string } };
  expect(set.focus).toBe("Pay particular attention to follow-up questions and clarification.");
  const secondSetResponse = await request.post("/api/speaking/sets", { headers: { Authorization: `Bearer ${token}` }, data: { name: "Grade 3 Conversation" } });
  expect(secondSetResponse.status()).toBe(201);
  const { set: secondSet } = await secondSetResponse.json() as { set: { id: string; name: string } };
  const addResponse = await request.post(`/api/speaking/sets/${set.id}/activities/${id}`, { headers: { Authorization: `Bearer ${token}` } });
  expect(addResponse.status()).toBe(200);

  await page.goto(`/quiz-strike/teacher/speaking/set/${set.id}`);
  await expect(page.getByText("Shared focus", { exact: true })).toBeVisible();
  await expect(page.getByText("Pay particular attention to follow-up questions and clarification.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Edit Set", exact: true }).click();
  const focusInput = page.getByRole("textbox", { name: /Shared focus/ });
  await focusInput.fill("Discard this focus");
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.getByRole("button", { name: "Edit Set", exact: true }).click();
  await expect(focusInput).toHaveValue(set.focus);
  await focusInput.fill("Notice clarification requests and follow-up questions.");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByText("Notice clarification requests and follow-up questions.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Launch Buying Clothes from Set", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/activity/${id}\\?sessionId=`));
  const sessionList = await request.get(`/api/speaking/activities/${id}/sessions`, { headers: { Authorization: `Bearer ${token}` } });
  const sessions = await sessionList.json() as { sessions: Array<{ speakingSetFocusSnapshot?: string }> };
  expect(sessions.sessions.at(0)?.speakingSetFocusSnapshot).toBe("Notice clarification requests and follow-up questions.");

  await page.goto("/quiz-strike/teacher/speaking");
  await page.getByLabel("Filter by source").selectOption("mine");
  await expect(page.locator(".speaking-activity-row")).toContainText("Buying Clothes");
  await page.getByLabel("More actions for Buying Clothes").click();
  await page.getByRole("button", { name: "Edit", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Edit Speaking Task" })).toBeVisible();
  await expect(page.getByLabel("Additional focus or class content")).toHaveValue("Notice polite requests and class vocabulary.");
  await page.goto("/quiz-strike/teacher/speaking");
  await page.getByLabel("Filter by source").selectOption("mine");
  await expect(page.locator(".speaking-activity-row")).toHaveCount(1);
  await page.getByLabel("More actions for Buying Clothes").click();
  await page.getByLabel("Add Buying Clothes to a Set").selectOption(secondSet.id);
  await expect(page.locator(".speaking-activity-row").filter({ hasText: "Buying Clothes" })).toContainText(secondSet.name);
  const duplicateButton = page.getByRole("button", { name: "Duplicate", exact: true });
  if (!(await duplicateButton.isVisible())) await page.getByLabel("More actions for Buying Clothes").click();
  await duplicateButton.click();
  await expect(page.getByText("Buying Clothes copy", { exact: true })).toBeVisible();
  await expect(page.locator(".speaking-activity-row")).toHaveCount(2);
  await page.getByLabel("More actions for Buying Clothes copy").click();
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "Delete", exact: true }).click();
  await expect(page.locator(".speaking-activity-row")).toHaveCount(1);
  await page.goto("/quiz-strike/teacher/speaking/activity/missing-audit-id/edit");
  await expect(page.getByRole("heading", { name: "Activity not found" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Save changes", exact: true })).toHaveCount(0);
});
