import { workplace, type WorkplaceSeed } from "./speakingWorkplaceBuilder.js";

const seeds: WorkplaceSeed[] = [
  {
    id: "hotel-welcome-guest",
    title: "Welcoming a Hotel Guest",
    category: "Hotels & Hospitality",
    categoryId: "hotels-hospitality",
    scenario: "A guest arrives at a hotel reception carrying luggage and looking for a calm, helpful first contact. The employee welcomes them and finds out what assistance they need.",
    aiRole: "International hotel guest",
    studentRole: "Hotel reception employee",
    goal: "Welcome the guest warmly, ask whether they have a reservation or need information, and guide them to the next useful step.",
    aiContext: "The guest has a reservation under Morgan Lee and wants to know where reception and the luggage area are. They may ask about breakfast or Wi-Fi after the initial welcome.",
    skills: ["Welcoming", "Asking questions", "Explaining", "Confirming information"],
    complication: "The guest is tired and asks two questions at once, so the employee should slow down and answer in a clear order.",
    conditions: ["Greet the guest professionally.", "Ask for the reservation name or purpose of the visit.", "Answer one immediate hotel question accurately.", "Offer a clear next step."],
    openingLine: "Good evening. We have just arrived, and we have a reservation under Morgan Lee.",
    steps: ["Greet and welcome the guest.", "Confirm the reservation name or request.", "Answer the first practical question.", "Explain where to go or what will happen next."],
    vocabulary: ["reservation", "reception", "guest", "luggage", "breakfast", "Wi-Fi"],
    targetExpressions: ["Welcome to our hotel.", "How may I help you?", "May I have the name on the reservation?", "Let me show you where to go.", "I hope you enjoy your stay."],
    durationSeconds: 180,
    difficulty: "easy"
  },
  {
    id: "hotel-check-in",
    title: "Checking In a Guest",
    category: "Hotels & Hospitality",
    categoryId: "hotels-hospitality",
    scenario: "A guest arrives to check in after a long journey. The receptionist confirms the reservation, room type and key stay information.",
    aiRole: "Guest checking in",
    studentRole: "Hotel front-desk employee",
    goal: "Confirm the reservation name and room type, explain breakfast, Wi-Fi and checkout time, and check whether the guest needs any immediate help.",
    aiContext: "The reservation is under Priya Shah for a double room. Breakfast is included, the hotel Wi-Fi is available, and the standard checkout time is 11:00. The guest asks whether a quiet room is possible; availability is not supplied.",
    skills: ["Welcoming", "Confirming information", "Explaining", "Clarifying"],
    complication: "The guest requests a quiet room, but the employee does not know whether one is available. They should check rather than promise it.",
    conditions: ["Confirm the reservation name and room type.", "Explain at least two stay details.", "Answer the checkout question accurately.", "Respond to the quiet-room request by checking availability.", "Offer the next step clearly."],
    openingLine: "Hello. I have a reservation under Priya Shah. Could I check in, please?",
    steps: ["Confirm the name and booking details.", "Explain the room and included services.", "Give checkout and Wi-Fi information.", "Handle the room request with an availability check."],
    vocabulary: ["check in", "double room", "included", "checkout", "quiet room", "availability"],
    targetExpressions: ["Let me confirm your reservation.", "You have a double room.", "Breakfast is included.", "Checkout is at…", "I'll check availability for you.", "Here is your room information."],
    durationSeconds: 240,
    difficulty: "easy"
  },
  {
    id: "hotel-explain-facilities",
    title: "Explaining Hotel Facilities",
    category: "Hotels & Hospitality",
    categoryId: "hotels-hospitality",
    scenario: "A guest has checked in and wants a quick orientation to the hotel, including Wi-Fi, breakfast, checkout, laundry and the front desk.",
    aiRole: "Guest learning about the hotel",
    studentRole: "Hotel reception employee",
    goal: "Explain the supplied hotel facilities and times clearly, check what matters most to the guest, and avoid inventing information about services that were not supplied.",
    aiContext: "Known information: breakfast is served in the ground-floor café from 7:00 to 10:00, Wi-Fi details are in the room, checkout is at 11:00, and the front desk can help with local questions. Laundry availability and gym hours are not supplied.",
    skills: ["Explaining", "Asking questions", "Confirming information", "Clarifying"],
    complication: "The guest asks about the gym or laundry service, but the employee does not have those details.",
    conditions: ["Ask what information the guest needs most.", "Explain breakfast, Wi-Fi and checkout accurately.", "Point the guest to the front desk or relevant location.", "Offer to check unknown facility information instead of guessing."],
    openingLine: "Could you give me a quick overview of the hotel and its facilities?",
    steps: ["Ask which services are important.", "Explain the known facilities and times.", "Check understanding or invite a question.", "Handle one unavailable detail professionally."],
    vocabulary: ["facility", "ground floor", "front desk", "laundry", "gym", "opening time"],
    targetExpressions: ["The breakfast café is on…", "Breakfast is served from…", "You can find the Wi-Fi details in…", "The front desk is available to help.", "I'll confirm that with the front desk."],
    durationSeconds: 240
  },
  {
    id: "hotel-room-request",
    title: "Helping with a Room Request",
    category: "Hotels & Hospitality",
    categoryId: "hotels-hospitality",
    scenario: "A guest calls reception because the room needs extra towels and the guest would prefer a quieter room if one becomes available.",
    aiRole: "Guest making a room request",
    studentRole: "Hotel reception employee",
    goal: "Listen to the request, confirm the room and items needed, contact the appropriate team, and explain what can be checked rather than promising an unavailable room.",
    aiContext: "The guest is in room 604 and needs two extra towels. They also hear noise from the corridor and ask about changing rooms. Housekeeping can be contacted; room availability is not supplied.",
    skills: ["Listening", "Requesting", "Confirming information", "Problem solving"],
    complication: "The guest asks for an immediate room change while the employee cannot see availability.",
    conditions: ["Acknowledge both parts of the request.", "Confirm the room number and towel quantity.", "Contact or offer to contact housekeeping.", "Check room availability rather than promising a move.", "Set a clear follow-up expectation."],
    openingLine: "Hello, this is room 604. Could we have two extra towels, please?",
    steps: ["Repeat the room number and request.", "Confirm the quantity and timing question.", "Explain that housekeeping will be contacted.", "Handle the quiet-room request with an availability check and next step."],
    vocabulary: ["extra towels", "room number", "housekeeping", "corridor", "noise", "room change"],
    targetExpressions: ["I understand.", "May I confirm your room number?", "I'll contact housekeeping.", "I'll check availability for you.", "I'll update you as soon as I know more."],
    durationSeconds: 240
  },
  {
    id: "hotel-guest-complaint",
    title: "Handling a Guest Complaint",
    category: "Hotels & Hospitality",
    categoryId: "hotels-hospitality",
    scenario: "A tired guest comes to reception because the room has a minor problem and the hallway was noisy during the night. The employee needs to handle the complaint calmly.",
    aiRole: "Guest making a complaint",
    studentRole: "Hotel front-desk employee",
    goal: "Listen without interrupting, acknowledge the inconvenience, apologize appropriately, gather useful details and offer a realistic next step.",
    aiContext: "The guest says the air conditioning was not working well and that there was noise outside the room. They want to know what the hotel can do. Do not require an admission of legal liability or promise a particular compensation.",
    skills: ["Listening", "Handling concerns", "Clarifying", "Problem solving"],
    complication: "The guest becomes frustrated and asks for a guaranteed room change or refund even though availability and policy are not supplied.",
    conditions: ["Let the guest explain the problem.", "Acknowledge the inconvenience and apologize appropriately.", "Ask for the room number and useful details.", "Offer a realistic check or contact with the responsible team.", "Avoid promising an unconfirmed remedy."],
    openingLine: "I had a difficult night. The room was noisy and the air conditioning did not seem to work properly.",
    steps: ["Listen and summarize the complaint.", "Apologize for the inconvenience.", "Ask what happened and confirm the room.", "Offer to contact maintenance or check another solution and explain follow-up."],
    vocabulary: ["complaint", "inconvenience", "air conditioning", "noise", "maintenance", "follow-up"],
    targetExpressions: ["I am sorry about the inconvenience.", "Thank you for letting us know.", "May I ask what time it started?", "I'll contact maintenance.", "I'll check what options are available.", "I'll follow up with you."],
    durationSeconds: 300,
    difficulty: "challenge"
  },
  {
    id: "hotel-local-recommendations",
    title: "Giving Local Recommendations",
    category: "Hotels & Hospitality",
    categoryId: "hotels-hospitality",
    scenario: "A visitor at the hotel wants a nearby dinner and a simple evening activity. The reception employee asks about preferences before making practical suggestions.",
    aiRole: "Guest asking for local advice",
    studentRole: "Hotel concierge or reception employee",
    goal: "Ask about food, distance and time preferences, recommend a suitable local option, and explain how the guest can reach it without inventing live information.",
    aiContext: "The guest wants a quiet Japanese dinner within a short walk and may be interested in a riverside walk afterward. The employee knows a restaurant near the station but does not know its current opening status.",
    skills: ["Asking questions", "Recommending", "Giving directions", "Confirming information"],
    complication: "The guest asks whether the restaurant is open tonight, but the employee has not checked the latest hours.",
    conditions: ["Ask about the guest's food and distance preferences.", "Recommend a place with a reason.", "Explain a simple route or landmark.", "Say that current opening information needs to be checked.", "Offer a backup idea."],
    openingLine: "We would like a quiet place for dinner nearby. Do you have a recommendation?",
    steps: ["Ask about cuisine, budget or walking distance.", "Suggest a suitable restaurant.", "Explain the route or nearby landmark.", "Check or offer to check opening information and give a backup."],
    vocabulary: ["recommendation", "nearby", "quiet", "walking distance", "opening hours", "backup"],
    targetExpressions: ["What kind of food would you prefer?", "There is a good option near…", "It is about a short walk from here.", "I'll check whether it is open tonight.", "Another possibility is…"],
    durationSeconds: 240
  },
  {
    id: "hotel-luggage-transport",
    title: "Helping with Luggage and Transportation",
    category: "Hotels & Hospitality",
    categoryId: "hotels-hospitality",
    scenario: "A guest is checking out later in the day but wants to visit a nearby area first. They ask about luggage storage, a taxi and the station.",
    aiRole: "Guest arranging departure help",
    studentRole: "Hotel reception employee",
    goal: "Clarify the guest's departure plan, explain the known luggage-storage process, ask what transport they need and arrange or check the appropriate next step.",
    aiContext: "The hotel can store luggage before departure, and reception can help call a taxi. The guest wants to reach the station around 16:00, but taxi waiting time and exact fare are not supplied.",
    skills: ["Asking questions", "Explaining", "Scheduling", "Confirming information"],
    complication: "The guest asks for an exact taxi arrival time and fare that the employee cannot guarantee.",
    conditions: ["Confirm the guest's checkout and travel timing.", "Explain luggage storage clearly.", "Ask whether a taxi or station directions are needed.", "Offer to arrange transport without guaranteeing unknown timing or cost.", "Confirm the next action."],
    openingLine: "We are checking out later, but could the hotel keep our luggage while we go out?",
    steps: ["Confirm the departure plan.", "Explain where and how luggage can be stored.", "Ask about the destination and time.", "Offer to call a taxi or explain the station route and flag unknown details."],
    vocabulary: ["luggage storage", "check out", "station", "taxi", "departure", "waiting time"],
    targetExpressions: ["We can store your luggage here.", "What time would you like to leave?", "Would you like me to call a taxi?", "I can't confirm the exact waiting time yet.", "I'll check that for you.", "Let me confirm your destination."],
    durationSeconds: 240
  },
  {
    id: "hotel-check-out",
    title: "Checking Out a Guest",
    category: "Hotels & Hospitality",
    categoryId: "hotels-hospitality",
    scenario: "A guest comes to the front desk to check out. The employee confirms the stay, handles a billing question carefully and closes the interaction warmly.",
    aiRole: "Guest checking out",
    studentRole: "Hotel front-desk employee",
    goal: "Confirm the guest name and room, explain the bill or check a question, confirm luggage or transport needs and say goodbye professionally.",
    aiContext: "The guest is staying in room 412 under Alex Chen. They ask why a café charge appears on the bill; the employee can review or confirm the item but should not invent an explanation.",
    skills: ["Confirming information", "Explaining", "Clarifying", "Welcoming"],
    complication: "The guest disputes one charge and is in a hurry to catch a train.",
    conditions: ["Confirm the room and guest name.", "Review the billing question calmly.", "Offer to check an unclear charge.", "Ask whether luggage storage or transportation is needed.", "Close the stay with a professional goodbye."],
    openingLine: "Good morning. I am checking out of room 412, but I have a question about the bill.",
    steps: ["Confirm the guest and room.", "Listen to the billing question.", "Check or explain only the known information.", "Offer transport or luggage help and close the interaction."],
    vocabulary: ["check out", "bill", "charge", "receipt", "luggage", "train"],
    targetExpressions: ["Let me confirm your room number.", "I'll check that charge for you.", "Here is your receipt.", "Would you like us to store your luggage?", "Can we help with transportation?", "Thank you for staying with us."],
    durationSeconds: 240
  }
];

export const HOTELS_HOSPITALITY_LIBRARY = seeds.map(workplace);

