import { workplace, type WorkplaceSeed } from "./speakingWorkplaceBuilder.js";

const seeds: WorkplaceSeed[] = [
  {
    id: "tourism-welcome-visitor",
    title: "Welcoming an International Visitor",
    category: "Tourism & Visitor Support",
    categoryId: "tourism-visitor-support",
    scenario: "An international visitor arrives at a local visitor-information desk in Japan and wants a simple orientation to the area.",
    aiRole: "International visitor",
    studentRole: "Visitor-information staff member",
    goal: "Welcome the visitor, ask what they hope to do, identify the time or mobility needs that matter and offer an appropriate first suggestion.",
    aiContext: "The visitor has one afternoon and is interested in food, a quiet cultural place and an easy route from the station. They do not know the area yet.",
    skills: ["Welcoming", "Asking questions", "Recommending", "Clarifying"],
    complication: "The visitor has limited time and asks for too many places, so the staff member should help prioritize.",
    conditions: ["Welcome the visitor clearly.", "Ask about interests and available time.", "Ask one practical question about access or distance.", "Offer a focused suggestion and next step."],
    openingLine: "Hello. I have one afternoon here and would like to see something local.",
    steps: ["Welcome the visitor.", "Ask about interests and time.", "Clarify practical needs.", "Recommend one or two appropriate options."],
    vocabulary: ["visitor", "afternoon", "local", "interest", "nearby", "priority"],
    targetExpressions: ["Welcome. What would you like to see?", "How much time do you have?", "What kind of place are you interested in?", "I would recommend…", "Let me help you choose."],
    durationSeconds: 180,
    difficulty: "easy",
    referenceItems: [
      { label: "Fictional area guide", detail: "Covered market: local food, five minutes east of the station. Riverside garden: quiet outdoor space, ten minutes north of the station." },
      { label: "Current information", detail: "Check opening times and access needs before confirming a visit; no live information is supplied." }
    ]
  },
  {
    id: "tourism-street-directions",
    title: "Giving Street Directions",
    category: "Tourism & Visitor Support",
    categoryId: "tourism-visitor-support",
    scenario: "A visitor is standing near the station and needs directions to a museum. The support employee uses landmarks and simple steps rather than a vague pointing gesture.",
    aiRole: "Visitor asking for directions",
    studentRole: "Local visitor-support staff member",
    goal: "Confirm the destination, give a clear route using landmarks and turns, check understanding and explain what to do if the visitor loses the route.",
    aiContext: "The museum is a ten-minute walk from the station. Walk straight past the convenience store, turn left at the post office and the museum is next to the public library. The visitor may ask for a taxi alternative.",
    skills: ["Giving directions", "Explaining", "Clarifying", "Asking questions"],
    complication: "The visitor repeats one step incorrectly, so the staff member must check understanding and rephrase it.",
    conditions: ["Confirm the destination.", "Give at least three route steps.", "Use a landmark or distance.", "Check that the visitor understands.", "Offer a sensible alternative if needed."],
    openingLine: "Excuse me. Could you tell me how to get to the city museum?",
    steps: ["Confirm the museum and starting point.", "Give the route one step at a time.", "Use landmarks and walking time.", "Ask the visitor to repeat or confirm the route."],
    vocabulary: ["straight", "turn left", "landmark", "post office", "next to", "walk"],
    targetExpressions: ["Go straight for about…", "Turn left at…", "It is next to…", "Does that route make sense?", "If you prefer, I can show you the taxi information."],
    durationSeconds: 240,
    difficulty: "easy",
    referenceItems: [
      { label: "Fictional museum route", detail: "From the station: walk straight past the convenience store; turn left at the post office; museum beside the public library. Approximately ten minutes on foot." },
      { label: "Alternative", detail: "Station taxi stand available; fares, wait times and accessibility need confirmation." }
    ]
  },
  {
    id: "tourism-train-bus",
    title: "Explaining Train or Bus Travel",
    category: "Tourism & Visitor Support",
    categoryId: "tourism-visitor-support",
    scenario: "A visitor wants to travel from Central Station to the Garden District by train and bus. Explain the route, boarding bay and train-to-bus transfer using the fictional guide.",
    aiRole: "Visitor planning local transport",
    studentRole: "Visitor-information staff member",
    goal: "Explain the train-to-bus route using the guide. Check the visitor's understanding and distinguish route notes from live departure information.",
    aiContext: "Use the fictional route guide: Green Line from Central Station to East Gate, then bus 12 from bay 3 to Garden District; about 35 minutes. The visitor is unsure where to transfer. Latest departures and today's bay status are not supplied.",
    skills: ["Explaining", "Giving directions", "Confirming information", "Clarifying"],
    complication: "The visitor asks for the next departure and whether bay 3 is in use today, but live schedule information is not available.",
    conditions: ["Confirm the destination.", "Explain the train-to-bus transfer accurately.", "Give the boarding bay and approximate travel time from the route notes.", "Offer to check any requested live schedule detail.", "Confirm the visitor's understanding."],
    openingLine: "What is the easiest way to get to the Garden District from here?",
    steps: ["Ask when the visitor plans to travel.", "Explain the train and bus route.", "Describe the transfer and travel time.", "Check or direct the visitor to the latest departure information."],
    vocabulary: ["train line", "transfer to a bus", "bus bay", "departure", "journey time", "latest information"],
    targetExpressions: ["Take the Green Line from Central Station.", "Get off at East Gate and transfer to bus 12.", "The bus leaves from bay 3.", "The journey takes about 35 minutes.", "Let me check the latest departure information for you."],
    durationSeconds: 240,
    referenceItems: [
      { label: "Fictional route guide", detail: "Green Line: Central Station → East Gate. Transfer there to bus 12, bay 3, for Garden District. Planned journey about 35 minutes." },
      { label: "Live checks", detail: "Next departure and today's boarding bay need confirmation; route notes are not a live timetable." }
    ]
  },
  {
    id: "tourism-recommend-place",
    title: "Recommending a Place to Visit",
    category: "Tourism & Visitor Support",
    categoryId: "tourism-visitor-support",
    scenario: "A couple asks a visitor-support employee to recommend one place for an afternoon in Japan. Their interests and walking ability need to be discovered first.",
    aiRole: "International visitors seeking a recommendation",
    studentRole: "Tourism support staff member",
    goal: "Ask about interests, time, weather and access needs, recommend a suitable place with reasons and explain how to reach it.",
    aiContext: "The visitors enjoy gardens and local food, have about three hours and prefer not to walk long distances. A riverside garden and a covered market are nearby, but current event details are not supplied.",
    skills: ["Asking questions", "Recommending", "Giving reasons", "Giving directions"],
    complication: "The visitors ask whether a special event is happening today, but that latest information must be checked.",
    conditions: ["Ask about interests, time and access.", "Offer two options or one well-supported recommendation.", "Explain why the recommendation fits.", "Give a practical route.", "Check the event question rather than guessing."],
    openingLine: "We have three hours this afternoon. Where would you recommend we go?",
    steps: ["Ask what the visitors enjoy.", "Clarify time and walking needs.", "Compare or recommend places.", "Explain the route and handle the current-event question."],
    vocabulary: ["recommend", "garden", "market", "covered", "walking distance", "event"],
    targetExpressions: ["What kind of places do you enjoy?", "Based on that, I would recommend…", "It is a good choice because…", "You can get there by…", "I'll check whether the event is running today."],
    durationSeconds: 240,
    referenceItems: [
      { label: "Fictional choices", detail: "Riverside garden: outdoor, ten-minute walk north from the station. Covered market: food stalls, five-minute walk east, shelter from rain." },
      { label: "Access and events", detail: "Ask about walking needs; check taxi options, step-free access and today's events before confirming." }
    ]
  },
  {
    id: "tourism-local-attraction",
    title: "Explaining a Local Attraction",
    category: "Tourism & Visitor Support",
    categoryId: "tourism-visitor-support",
    scenario: "A visitor asks about a historic local attraction before deciding whether to go. The employee explains what it is, how long a visit may take and what is confirmed.",
    aiRole: "Visitor asking about an attraction",
    studentRole: "Local tourism staff member",
    goal: "Describe the attraction in accessible English, answer questions about access and time, and distinguish supplied facts from information that needs confirmation.",
    aiContext: "The attraction is a restored riverside merchant house with an English information leaflet. Visitors usually spend about one hour there. The supplied information does not include today's opening hours or photography rules.",
    skills: ["Explaining", "Sharing information", "Clarifying", "Confirming information"],
    complication: "The visitor asks whether it is open now and whether photos are allowed, but the employee has no live confirmation.",
    conditions: ["Explain what visitors can see.", "Give the supplied visit-time information.", "Answer an access question clearly.", "Flag opening hours or photography rules for checking.", "Offer a practical next step."],
    openingLine: "What is interesting about the old merchant house? Is it worth visiting?",
    steps: ["Ask what the visitor would like to know.", "Describe the attraction and typical visit length.", "Explain how to reach it.", "Check the current-hours and photography questions."],
    vocabulary: ["attraction", "restored", "merchant house", "leaflet", "visit", "photography"],
    targetExpressions: ["It is known for…", "Visitors can see…", "A visit usually takes about…", "I don't have the latest hours here.", "Let me check that information for you."],
    durationSeconds: 240,
    referenceItems: [
      { label: "Fictional merchant house", detail: "Restored riverside merchant house with an English leaflet; typical visit about one hour." },
      { label: "Route", detail: "From the station, follow Riverside Street for about ten minutes; the house is beside the footbridge." },
      { label: "Checks", detail: "Today's opening hours, photography rules and step-free access are not confirmed." }
    ]
  },
  {
    id: "tourism-lost-visitor",
    title: "Helping a Visitor Who Is Lost",
    category: "Tourism & Visitor Support",
    categoryId: "tourism-visitor-support",
    scenario: "A visitor is confused near a station while reading a phone map. Establish where they are and use the route notes to help them reach the Sakura Street hotel.",
    aiRole: "Visitor who is lost",
    studentRole: "Visitor-support employee or local helper",
    goal: "Reassure the visitor, identify where they are and where they need to go, use the map or landmarks to give a clear next route and check whether further help is needed.",
    aiContext: "Reveal when asked: the visitor is at South Exit, wants the Sakura Street hotel and is reading a phone map upside down. Use the route notes. They need short directions and confirmation of which station exit to use.",
    skills: ["Listening", "Giving directions", "Clarifying", "Problem solving"],
    complication: "The visitor is looking at the map upside down and thinks the hotel is in the opposite direction.",
    conditions: ["Reassure the visitor politely.", "Ask for the destination and current landmark.", "Clarify the correct station exit or direction.", "Give manageable route steps.", "Check understanding and offer another support option."],
    openingLine: "I think I am lost. I am trying to find the Sakura Street hotel.",
    steps: ["Acknowledge and reassure.", "Ask where the visitor came from and what they can see.", "Orient the map and identify the exit.", "Give the next steps and check understanding."],
    vocabulary: ["lost", "map", "exit", "landmark", "opposite", "hotel"],
    targetExpressions: ["Don't worry; let's work it out.", "Where did you come from?", "Which exit are you near?", "The hotel is in this direction.", "Let me show you on the map.", "Could you check the next landmark?"],
    durationSeconds: 300,
    difficulty: "challenge",
    referenceItems: [
      { label: "Fictional station route", detail: "Follow signs through the public station passage to North Exit. Outside North Exit, follow Sakura Street for five minutes; the hotel is on the right beside the bakery." },
      { label: "Extra help", detail: "Use landmarks and station signs; offer to check access or ask station staff if the route is unclear. No built-in map is required." }
    ]
  },
  {
    id: "tourism-tickets-reservations",
    title: "Helping with Tickets or Reservations",
    category: "Tourism & Visitor Support",
    categoryId: "tourism-visitor-support",
    scenario: "A visitor wants tickets for a popular attraction and asks whether a same-day reservation is possible. The employee explains the known booking route and checks unknown availability.",
    aiRole: "Visitor arranging an attraction visit",
    studentRole: "Tourism information or ticket-desk employee",
    goal: "Clarify the requested date and number of people, explain the supplied ticket process, and check current reservation availability without promising a ticket.",
    aiContext: "The visitor wants two tickets for the fictional merchant house this afternoon. Use the booking notes. Availability and prices are not supplied; accept a clear explanation of how to check rather than demand an invented result.",
    skills: ["Asking questions", "Explaining", "Confirming information", "Problem solving"],
    complication: "The visitor has limited time and asks the employee to guarantee two tickets now.",
    conditions: ["Confirm date, time and number of visitors.", "Explain the known reservation route.", "Check or direct the visitor to current availability.", "Avoid promising tickets or prices that are not confirmed.", "Offer a backup plan if needed."],
    openingLine: "Could you help us get two tickets for the attraction this afternoon?",
    steps: ["Ask about the visit time and group size.", "Explain the available booking route.", "Check current availability or direct the visitor to the official source.", "Offer a backup attraction or time if tickets are unavailable."],
    vocabulary: ["ticket", "reservation", "availability", "official", "same day", "backup"],
    targetExpressions: ["For what date and time?", "How many tickets do you need?", "Let me check availability.", "I can't guarantee a ticket until it is confirmed.", "The official booking desk can help with…", "Another option would be…"],
    durationSeconds: 300,
    referenceItems: [{ label: "Fictional booking notes", detail: "The merchant house has an official booking counter and online reservation page. Confirm date, time and party size there; current availability and prices are unknown. Do not claim a reservation has been made." }]
  },
  {
    id: "tourism-change-plan",
    title: "Handling a Change of Plan",
    category: "Tourism & Visitor Support",
    categoryId: "tourism-visitor-support",
    scenario: "Rain changes an international visitor's outdoor sightseeing plan. The tourism employee listens to what has already been booked and helps create a practical indoor alternative.",
    aiRole: "Visitor whose plan changed",
    studentRole: "Tourism support employee",
    goal: "Help the visitor choose an indoor plan that fits before dinner. Explain which opening times or bookings still need checking.",
    aiContext: "The visitor planned a garden walk and an outdoor market but now wants indoor places near the station. They have a dinner reservation at 19:00. Current weather, attraction hours and same-day availability are not supplied.",
    skills: ["Listening", "Asking questions", "Recommending", "Problem solving"],
    complication: "The visitor asks for an indoor attraction that may be closed today and wants a route that fits before dinner.",
    conditions: ["Acknowledge the change and ask what matters most.", "Confirm the available time and dinner constraint.", "Offer at least two sensible alternatives.", "Check current opening or reservation information.", "Agree on a practical revised plan."],
    openingLine: "It is raining, so our outdoor plan will not work. Could you help us change it?",
    steps: ["Ask what the visitor still wants to experience.", "Confirm time and existing reservation.", "Suggest indoor alternatives near a practical route.", "Check current information and summarize the new plan."],
    vocabulary: ["change of plan", "rainy", "indoor", "reservation", "available", "route"],
    targetExpressions: ["Let's look at some indoor options.", "What would you still like to see?", "What time is your dinner reservation?", "We could consider the museum or covered market.", "I'll check the opening times before we decide.", "Let me summarize the plan."],
    durationSeconds: 300,
    difficulty: "challenge",
    referenceItems: [
      { label: "Fictional indoor options", detail: "City museum: ten-minute walk from the station, about one hour to visit. Covered market: five-minute walk east, food stalls under cover." },
      { label: "Plan checks", detail: "Confirm current hours, travel conditions and any booking before promising that a plan will fit. No live availability is supplied." }
    ]
  }
];

export const TOURISM_VISITOR_SUPPORT_LIBRARY = seeds.map(workplace);
