import { workplace, type WorkplaceSeed } from "./speakingWorkplaceBuilder.js";

const seeds: WorkplaceSeed[] = [
  {
    id: "office-introduce-yourself",
    title: "Introducing Yourself at Work",
    category: "Office & Business",
    categoryId: "office-business",
    scenario: "A new employee joins a small international team and meets a colleague from another department. They exchange roles, responsibilities and a simple work-related question.",
    aiRole: "New colleague",
    studentRole: "Employee introducing themselves",
    goal: "Introduce yourself, explain your role in simple English, ask about the colleague's work and establish a comfortable next connection.",
    aiContext: "The colleague works with the customer-support team and is curious about the employee's role. The employee can choose realistic details but should keep the introduction clear and concise.",
    skills: ["Welcoming", "Sharing information", "Asking questions", "Follow-up questions"],
    complication: "The colleague uses an unfamiliar department name, so the employee asks a polite clarification question.",
    conditions: ["Say your name and team.", "Explain one responsibility.", "Ask a relevant question about the colleague's work.", "Clarify one unfamiliar detail and close naturally."],
    openingLine: "Hi, I do not think we have met yet. I am Maya from customer support.",
    steps: ["Greet and introduce yourself.", "Explain your role in one or two sentences.", "Ask about the colleague's work.", "Clarify one detail and suggest staying in touch."],
    vocabulary: ["department", "team", "role", "responsibility", "support", "colleague"],
    targetExpressions: ["Nice to meet you.", "I work on…", "My main responsibility is…", "What does your team handle?", "Could you explain that briefly?", "I look forward to working with you."],
    durationSeconds: 180,
    difficulty: "easy"
  },
  {
    id: "office-welcome-visitor",
    title: "Welcoming a Business Visitor",
    category: "Office & Business",
    categoryId: "office-business",
    scenario: "A visitor arrives for a meeting with the sales manager. The reception employee confirms the visitor's name and company and explains what will happen while the host is contacted.",
    aiRole: "Business visitor arriving at reception",
    studentRole: "Office receptionist or host employee",
    goal: "Welcome the visitor, confirm the appointment, contact the host and explain the waiting location without inventing a meeting delay or access policy.",
    aiContext: "The visitor is Jordan Smith from North Star Travel and has a 10:30 meeting with Ken Ito. The host is not yet at reception. The visitor asks whether they should wait in the lobby or meeting room; the employee should check.",
    skills: ["Welcoming", "Confirming information", "Explaining", "Scheduling"],
    complication: "The visitor asks for an exact waiting time, but the host's arrival is not confirmed.",
    conditions: ["Greet and identify the visitor.", "Confirm the appointment details.", "Contact the host.", "Explain the waiting arrangement or check it.", "Avoid promising an arrival time that is unknown."],
    openingLine: "Good morning. I am here to see Ken Ito at 10:30.",
    steps: ["Welcome the visitor.", "Confirm name, company and host.", "Contact the host and explain the current status.", "Offer a waiting place and handle the timing question."],
    vocabulary: ["appointment", "visitor", "reception", "host", "lobby", "meeting room"],
    targetExpressions: ["Welcome to our office.", "May I have your name and company?", "Let me contact Ken Ito.", "Please make yourself comfortable while I check.", "I can't confirm the waiting time yet.", "I'll update you as soon as I know."],
    durationSeconds: 240,
    difficulty: "easy"
  },
  {
    id: "office-client-small-talk",
    title: "Making Small Talk with a Client",
    category: "Office & Business",
    categoryId: "office-business",
    scenario: "A client arrives early for a meeting. The employee makes brief, respectful small talk about the journey and the client's visit before moving to the meeting purpose.",
    aiRole: "Client visiting the office",
    studentRole: "Employee hosting the client",
    goal: "Make natural small talk, ask one or two appropriate questions, notice when the client is ready to move on and transition to the meeting.",
    aiContext: "The client traveled from Osaka by train and is visiting for a product discussion. They prefer practical conversation and do not want a long personal exchange.",
    skills: ["Welcoming", "Asking questions", "Follow-up questions", "Confirming information"],
    complication: "The client mentions a train delay and seems pressed for time, so the employee should keep the conversation brief and relevant.",
    conditions: ["Welcome the client politely.", "Ask about the journey or visit.", "Respond naturally to the answer.", "Check the client's time or transition smoothly to the meeting."],
    openingLine: "Thanks for meeting with me. The train was a little delayed, but I arrived safely.",
    steps: ["Welcome the client.", "Ask one light question about the journey or visit.", "Listen and respond briefly.", "Confirm the meeting purpose and move to the next step."],
    vocabulary: ["journey", "delay", "visit", "meeting", "comfortable", "agenda"],
    targetExpressions: ["I hope your journey was comfortable.", "How was the trip?", "Thank you for coming.", "Would you like some water?", "Shall we get started?", "Let me confirm today's purpose."],
    durationSeconds: 180
  },
  {
    id: "office-arrange-meeting",
    title: "Arranging a Meeting",
    category: "Office & Business",
    categoryId: "office-business",
    scenario: "A colleague and a client need to find a time for a 30-minute online meeting next week. The employee proposes options, checks time zones and confirms the final arrangement.",
    aiRole: "Colleague or client scheduling a meeting",
    studentRole: "Employee arranging the meeting",
    goal: "Clarify the meeting purpose and length, offer available times, confirm the time zone and participants, and summarize the agreed arrangement.",
    aiContext: "The client is in Singapore and can meet Tuesday or Wednesday afternoon Japan time. The meeting should take 30 minutes and include the employee's manager. The exact video platform is not supplied.",
    skills: ["Scheduling", "Asking questions", "Confirming information", "Clarifying"],
    complication: "The client suggests a time that is fine in Singapore but early in Japan, so the employee checks the time zone before agreeing.",
    conditions: ["Confirm the purpose and duration.", "Offer at least two possible times.", "Check the time zone and participants.", "Clarify the meeting platform if needed.", "Repeat the final arrangement."],
    openingLine: "Could we arrange a short meeting next week to discuss the new customer survey?",
    steps: ["Ask about duration and participants.", "Offer suitable times.", "Check the time zone.", "Confirm platform and summarize the final booking."],
    vocabulary: ["schedule", "available", "time zone", "duration", "participant", "online"],
    targetExpressions: ["When would be convenient for you?", "Would Tuesday afternoon work?", "Let me check the time zone.", "The meeting will take about 30 minutes.", "Let me confirm the details.", "I'll send the meeting information."],
    durationSeconds: 240
  },
  {
    id: "office-work-problem",
    title: "Explaining a Simple Work Problem",
    category: "Office & Business",
    categoryId: "office-business",
    scenario: "A colleague is waiting for a customer report, but one data file has not arrived. The employee explains the problem, gives what is known and proposes a practical next step.",
    aiRole: "Colleague waiting for a report",
    studentRole: "Employee explaining a work problem",
    goal: "State what is delayed, explain the effect without blaming someone, offer a realistic temporary solution and agree on a follow-up time.",
    aiContext: "The sales file is ready, but the delivery file from another team has not arrived. The report was expected this morning. The employee can send a partial draft now and follow up at 15:00.",
    skills: ["Explaining", "Problem solving", "Clarifying", "Confirming information"],
    complication: "The colleague needs something to show a customer soon and asks whether the complete report can be guaranteed by noon.",
    conditions: ["Explain the problem and impact clearly.", "Say what information is available.", "Suggest a partial or temporary solution.", "Avoid guaranteeing an unknown delivery time.", "Agree on a follow-up."],
    openingLine: "I was expecting the report this morning. Is there a problem?",
    steps: ["Explain what has arrived and what is missing.", "Describe the current effect.", "Offer a partial report or alternative.", "Check the priority and confirm when you will update them."],
    vocabulary: ["delay", "file", "report", "partial", "complete", "follow-up"],
    targetExpressions: ["One file has not arrived yet.", "Here is what I can provide now.", "I can send a partial draft.", "I can't guarantee the final time yet.", "I'll update you by…", "Would that help for now?"],
    durationSeconds: 300,
    difficulty: "challenge"
  },
  {
    id: "office-clarify",
    title: "Asking for Clarification",
    category: "Office & Business",
    categoryId: "office-business",
    scenario: "A manager gives a brief request about updating a customer list, but one requirement is unclear. The employee asks focused questions and repeats the agreed task.",
    aiRole: "Manager giving a work request",
    studentRole: "Employee clarifying the request",
    goal: "Identify what is unclear, ask specific clarification questions, confirm the output and deadline and summarize the request in your own words.",
    aiContext: "The manager wants the customer list 'updated before Friday.' It is unclear whether the employee should add new contacts, remove duplicates, or change the format. The employee should ask rather than assume.",
    skills: ["Clarifying", "Asking questions", "Confirming information", "Listening"],
    complication: "The manager is busy and gives a short answer, so the employee needs to confirm the most important points politely.",
    conditions: ["State which part is unclear.", "Ask at least two useful clarification questions.", "Confirm the required format or content.", "Confirm the deadline.", "Summarize the agreed task."],
    openingLine: "Could you update the customer list before Friday?",
    steps: ["Listen for the ambiguous parts.", "Ask about content, format and priority.", "Confirm the deadline.", "Repeat the task and check that your understanding is correct."],
    vocabulary: ["clarify", "customer list", "duplicate", "format", "deadline", "priority"],
    targetExpressions: ["Could I clarify one point?", "Do you mean that I should…?", "Which format would you prefer?", "What is the priority?", "Let me repeat that to make sure I understand.", "I will complete it by…"],
    durationSeconds: 240
  },
  {
    id: "office-project-update",
    title: "Giving a Short Project Update",
    category: "Office & Business",
    categoryId: "office-business",
    scenario: "A colleague asks for a brief update on a small website translation project. The employee reports what is complete, what is in progress and what needs attention.",
    aiRole: "Colleague asking for a project update",
    studentRole: "Project team member",
    goal: "Give a concise status update, mention one completed item, one current task and one risk or delay, then propose the next step.",
    aiContext: "The homepage translation is complete. The booking page is in progress. A terminology question is waiting for the client's confirmation. The internal target is Friday, but the final date depends on that reply.",
    skills: ["Sharing information", "Explaining", "Confirming information", "Problem solving"],
    complication: "The colleague asks whether Friday is certain even though the client response is still missing.",
    conditions: ["State the project purpose or scope briefly.", "Report completed and current work.", "Explain the open question or risk.", "Avoid guaranteeing a date that depends on a reply.", "Suggest the next action."],
    openingLine: "Could you give me a quick update on the website translation?",
    steps: ["Give the short overall status.", "Say what is complete and in progress.", "Explain the client-dependent point.", "Confirm the next follow-up and expected timing."],
    vocabulary: ["update", "complete", "in progress", "terminology", "client", "target"],
    targetExpressions: ["The current status is…", "We have completed…", "We are working on…", "One point is still waiting for confirmation.", "The timing depends on…", "The next step is…"],
    durationSeconds: 300
  },
  {
    id: "office-client-request",
    title: "Handling a Customer or Client Request",
    category: "Office & Business",
    categoryId: "office-business",
    scenario: "A client asks the employee to add a new report section and send it by tomorrow. The employee clarifies the need, checks what is possible and agrees on a realistic next step.",
    aiRole: "Client making a new request",
    studentRole: "Account or project employee",
    goal: "Understand the client's request, ask about the priority and required detail, explain what can be confirmed and propose a realistic delivery or check-in.",
    aiContext: "The client wants a regional sales comparison added to a report by tomorrow afternoon. The employee knows the source data may need another team's input and cannot promise the finished section until that is checked.",
    skills: ["Listening", "Clarifying", "Negotiating", "Confirming information"],
    complication: "The client says the request is urgent and asks for a guarantee before the employee has checked the data or team capacity.",
    conditions: ["Listen and restate the requested change.", "Ask what detail and deadline matter most.", "Explain the dependency or information to check.", "Offer a realistic partial update or confirmation time.", "Do not promise an unverified delivery."],
    openingLine: "Could you add a regional sales comparison to the report by tomorrow afternoon?",
    steps: ["Clarify the desired comparison and format.", "Confirm the deadline and priority.", "Explain what needs checking.", "Offer a realistic next update and summarize the agreement."],
    vocabulary: ["request", "regional", "comparison", "deadline", "data", "capacity"],
    targetExpressions: ["Let me make sure I understand the request.", "Which detail is most important?", "I need to check the source data first.", "I can confirm the timing after I check.", "I can send a preliminary update by…", "I'll follow up with you."],
    durationSeconds: 300,
    difficulty: "challenge"
  }
];

export const OFFICE_BUSINESS_LIBRARY = seeds.map(workplace);

