import { workplace, type WorkplaceSeed } from "./speakingWorkplaceBuilder.js";

const seeds: WorkplaceSeed[] = [
  {
    id: "restaurant-welcome-seat",
    title: "Welcoming and Seating Customers",
    category: "Restaurants & Cafés",
    categoryId: "restaurants-cafes",
    scenario: "Two international guests arrive at a busy café. One person made a reservation, and the server needs to confirm the party size and guide them to a table.",
    aiRole: "Customer arriving at a café",
    studentRole: "Restaurant or café server",
    goal: "Welcome the guests, confirm the reservation or party size, explain the seating wait if needed and begin the service naturally.",
    aiContext: "The guests have a reservation under Daniel Kim for two people. They prefer a quiet table, but the employee does not know whether one is currently free.",
    skills: ["Welcoming", "Confirming information", "Asking questions", "Explaining"],
    complication: "The quiet table is not confirmed, so the server should check rather than promise it.",
    conditions: ["Welcome the guests politely.", "Confirm the reservation name and party size.", "Ask about a seating preference.", "Explain or check the available table and guide the guests to the next step."],
    openingLine: "Good evening. We have a reservation under Daniel Kim for two.",
    steps: ["Welcome the party.", "Confirm the reservation and number of guests.", "Ask about seating needs.", "Explain the table or waiting step and offer menus."],
    vocabulary: ["reservation", "party", "table", "quiet", "menu", "available"],
    targetExpressions: ["Welcome. Do you have a reservation?", "May I have the name, please?", "Your table is ready.", "I'll check whether a quieter table is available.", "Right this way, please."],
    durationSeconds: 180,
    difficulty: "easy"
  },
  {
    id: "restaurant-explain-menu",
    title: "Explaining the Menu",
    category: "Restaurants & Cafés",
    categoryId: "restaurants-cafes",
    scenario: "A customer is reading a menu and asks what several dishes contain, how large the portions are and whether a set includes a drink.",
    aiRole: "Customer deciding what to order",
    studentRole: "Restaurant or café server",
    goal: "Explain supplied menu information clearly, ask what the customer prefers and identify any ingredient question that must be checked with the kitchen.",
    aiContext: "The menu includes a grilled fish set with rice and soup, a vegetable pasta, and a chicken sandwich. The set includes a drink. Exact soup ingredients are not supplied.",
    skills: ["Explaining", "Asking questions", "Clarifying", "Taking orders"],
    complication: "The customer asks whether the soup contains a particular ingredient that the menu does not list.",
    conditions: ["Describe at least two menu options.", "Answer the supplied set and drink question.", "Ask about the customer's preference.", "Offer to check an unknown ingredient with the kitchen."],
    openingLine: "Could you explain a few of these dishes? I am choosing between the pasta and the fish set.",
    steps: ["Ask what the customer is looking for.", "Explain the supplied dishes and set details.", "Clarify portion or drink questions.", "Check any unknown ingredient rather than guessing."],
    vocabulary: ["dish", "set meal", "ingredient", "portion", "soup", "kitchen"],
    targetExpressions: ["This dish comes with…", "The set includes a drink.", "Would you prefer something light?", "Let me check the ingredients with the kitchen.", "I don't want to give you incorrect information."],
    durationSeconds: 240,
    difficulty: "easy"
  },
  {
    id: "restaurant-take-order",
    title: "Taking a Food Order",
    category: "Restaurants & Cafés",
    categoryId: "restaurants-cafes",
    scenario: "A server takes an order from a small group whose members are ready at different times. The order includes a main dish, a drink and one change.",
    aiRole: "Customer placing a group order",
    studentRole: "Restaurant server",
    goal: "Ask who is ready, take the food and drink choices accurately, confirm a modification and repeat the order before sending it to the kitchen.",
    aiContext: "Three customers are ordering: one wants vegetable pasta with no cheese, one wants the chicken set and iced tea, and one needs another minute. The customer may speak quickly or correct one detail.",
    skills: ["Taking orders", "Clarifying", "Confirming information", "Asking questions"],
    complication: "One guest changes the drink after the server repeats the order.",
    conditions: ["Check who is ready to order.", "Record main dishes and drinks accurately.", "Confirm the no-cheese modification.", "Repeat the order and handle the changed drink.", "Explain what will happen next."],
    openingLine: "Are you ready to order, or would you like a few more minutes?",
    steps: ["Check readiness and take one order at a time.", "Ask clarifying questions about choices.", "Repeat the complete order.", "Correct the changed item and confirm the kitchen will receive it."],
    vocabulary: ["order", "main dish", "drink", "change", "repeat", "kitchen"],
    targetExpressions: ["May I take your order?", "What would you like to drink?", "Would you like anything changed?", "Let me repeat that.", "I'll send this to the kitchen now."],
    durationSeconds: 240
  },
  {
    id: "restaurant-dietary-questions",
    title: "Handling Dietary Questions",
    category: "Restaurants & Cafés",
    categoryId: "restaurants-cafes",
    scenario: "A customer has a serious food allergy and needs reliable information before ordering. The server must ask precise questions and consult the kitchen when the menu is not enough.",
    aiRole: "Customer asking about dietary needs",
    studentRole: "Restaurant server",
    goal: "Listen carefully to the allergy or dietary question, identify what is known, avoid inventing ingredient or cross-contact information, and check with the kitchen before recommending a dish.",
    aiContext: "The customer says they have a nut allergy and asks about the sauce on a noodle dish. The menu does not provide enough detail. The server should not give medical advice or guarantee safety without checking the kitchen.",
    skills: ["Listening", "Clarifying", "Confirming information", "Problem solving"],
    complication: "The customer asks whether a small amount would be safe. The employee must not make a medical judgment.",
    conditions: ["Ask the customer to explain the dietary concern.", "Repeat the key allergy information to confirm understanding.", "Say that the ingredient information must be checked.", "Contact or offer to contact the kitchen.", "Avoid medical advice or an unsupported safety guarantee."],
    openingLine: "Before I order, I need to ask about a nut allergy. Do you know what is in the sauce?",
    steps: ["Listen and clarify the allergy question.", "Repeat the important detail.", "Explain what the menu can and cannot confirm.", "Check with the kitchen and return with verified information or another option."],
    vocabulary: ["allergy", "ingredient", "sauce", "kitchen", "dietary", "confirm"],
    targetExpressions: ["Thank you for telling me.", "Let me check with the kitchen.", "I don't want to guess about the ingredients.", "I'll confirm what we can offer.", "Would you like to wait while I check?"],
    durationSeconds: 300,
    difficulty: "challenge"
  },
  {
    id: "restaurant-recommend-food-drinks",
    title: "Recommending Food and Drinks",
    category: "Restaurants & Cafés",
    categoryId: "restaurants-cafes",
    scenario: "A visitor wants a local meal but does not know the menu. The server asks about taste, portion and drink preferences before making a recommendation.",
    aiRole: "Visitor choosing food and a drink",
    studentRole: "Restaurant server",
    goal: "Discover the customer's preferences, recommend a dish and drink with reasons, explain a relevant detail and check whether the customer is ready to order.",
    aiContext: "The customer wants something not too spicy, a moderate portion and a non-alcoholic drink. They are open to a local-style dish but want to understand it first.",
    skills: ["Asking questions", "Recommending", "Explaining", "Giving reasons"],
    complication: "The customer likes the recommendation but asks whether there is a smaller portion or a less spicy version.",
    conditions: ["Ask about taste, portion and drink preferences.", "Recommend a suitable dish and drink.", "Give a clear reason for the recommendation.", "Answer the portion or spice follow-up accurately or offer to check.", "Invite the customer to decide."],
    openingLine: "I would like to try something local, but I do not know what to choose.",
    steps: ["Ask what flavors and portion the customer prefers.", "Suggest a dish and drink.", "Explain the key features and reason.", "Respond to the follow-up and confirm the order decision."],
    vocabulary: ["recommend", "spicy", "portion", "local", "non-alcoholic", "flavor"],
    targetExpressions: ["What kind of flavors do you prefer?", "I would recommend…", "It is popular because…", "This may be a good choice if…", "Let me check whether a smaller portion is available."],
    durationSeconds: 240
  },
  {
    id: "restaurant-unavailable-item",
    title: "Handling an Unavailable Item",
    category: "Restaurants & Cafés",
    categoryId: "restaurants-cafes",
    scenario: "A customer orders a seasonal dessert, but the kitchen has just sold the last portion. The server explains the situation and helps the customer choose an alternative.",
    aiRole: "Customer whose first choice is unavailable",
    studentRole: "Restaurant server",
    goal: "Explain that an item is unavailable politely, apologize appropriately, offer realistic alternatives and confirm the revised order.",
    aiContext: "The seasonal matcha parfait is sold out. The café still has a fruit tart and a vanilla pudding. The customer is disappointed and asks when the parfait will be available again; no future stock information is supplied.",
    skills: ["Handling concerns", "Recommending", "Clarifying", "Taking orders"],
    complication: "The customer asks the server to promise that the dessert will be back tomorrow.",
    conditions: ["State clearly that the requested item is unavailable.", "Acknowledge the disappointment.", "Offer at least one alternative.", "Avoid promising future availability.", "Confirm the replacement choice."],
    openingLine: "I would like the matcha parfait, please.",
    steps: ["Check and explain the item status.", "Apologize for the inconvenience.", "Offer the available alternatives.", "Handle the future-availability question and confirm the new choice."],
    vocabulary: ["sold out", "unavailable", "seasonal", "alternative", "replacement", "available"],
    targetExpressions: ["I'm sorry, but that item is sold out.", "Would you like to try… instead?", "This is another popular choice.", "I can't confirm when it will be available again.", "Let me confirm your new order."],
    durationSeconds: 240
  },
  {
    id: "restaurant-customer-problem",
    title: "Responding to a Customer Problem",
    category: "Restaurants & Cafés",
    categoryId: "restaurants-cafes",
    scenario: "A customer says the order is not what they expected: the drink is wrong and the main dish is missing a requested change. The server must correct the problem.",
    aiRole: "Customer reporting an order problem",
    studentRole: "Restaurant server",
    goal: "Listen, apologize appropriately, confirm the original order, contact the kitchen or bar and explain the next step without promising an unrealistic timing.",
    aiContext: "The customer ordered iced tea and pasta without cheese, but received hot tea and pasta with cheese. The kitchen's exact correction time is not supplied.",
    skills: ["Listening", "Handling concerns", "Confirming information", "Problem solving"],
    complication: "The customer is on a short lunch break and asks how long the correction will take.",
    conditions: ["Let the customer explain the problem.", "Acknowledge and apologize.", "Confirm the drink and food correction needed.", "Contact the appropriate team.", "Give a realistic update or say that timing needs to be checked."],
    openingLine: "Excuse me. I ordered iced tea and pasta without cheese, but this is not what I received.",
    steps: ["Listen without interrupting.", "Repeat the correction details.", "Apologize and contact the kitchen or bar.", "Explain what will happen and check the timing question."],
    vocabulary: ["incorrect", "correction", "without cheese", "replace", "kitchen", "timing"],
    targetExpressions: ["I'm sorry about that.", "Let me confirm what you ordered.", "I'll ask the kitchen to correct it.", "I'll check how long it will take.", "Thank you for your patience."],
    durationSeconds: 300,
    difficulty: "challenge"
  },
  {
    id: "restaurant-payment-goodbye",
    title: "Taking Payment and Saying Goodbye",
    category: "Restaurants & Cafés",
    categoryId: "restaurants-cafes",
    scenario: "A group finishes dinner and asks for the bill. The server confirms whether they will pay together or split the bill, handles a card-payment question and says goodbye.",
    aiRole: "Customer finishing a meal",
    studentRole: "Restaurant server",
    goal: "Confirm the payment arrangement, provide or explain the bill, check the payment method and close the interaction politely.",
    aiContext: "There are four guests. They want to split the bill evenly if the restaurant can do so. The employee knows the total but should check any exact split or payment policy that is not supplied.",
    skills: ["Confirming information", "Clarifying", "Explaining", "Welcoming"],
    complication: "The guests change from one payment to separate payments and ask whether each person can use a card.",
    conditions: ["Ask how the group would like to pay.", "Explain the bill or total clearly.", "Check the split-payment question rather than inventing policy.", "Confirm the final payment arrangement.", "Thank the guests and say goodbye naturally."],
    openingLine: "Everything was delicious. Could we have the bill, please?",
    steps: ["Bring or explain the bill.", "Ask whether payment is together or separate.", "Check the card or split question.", "Confirm payment and close warmly."],
    vocabulary: ["bill", "total", "split", "evenly", "card", "receipt"],
    targetExpressions: ["Of course. I'll bring the bill.", "Would you like to pay together or separately?", "Let me check whether we can split it that way.", "Here is your receipt.", "Thank you very much. Have a good evening."],
    durationSeconds: 240
  }
];

export const RESTAURANTS_CAFES_LIBRARY = seeds.map(workplace);

