import { workplace, type WorkplaceSeed } from "./speakingWorkplaceBuilder.js";

const seeds: WorkplaceSeed[] = [
  {
    id: "retail-greet-customer",
    title: "Greeting a Customer in a Store",
    category: "Retail & Customer Service",
    categoryId: "retail-customer-service",
    scenario: "An international customer enters a specialty store and looks around. The employee gives them space while making a helpful first contact.",
    aiRole: "Customer entering a store",
    studentRole: "Retail store employee",
    goal: "Greet the customer, offer help without pressure, find out whether they are browsing or looking for something specific, and point them toward a useful area.",
    aiContext: "The customer is browsing for a gift but is not ready to explain everything at once. They appreciate a short, natural welcome and may ask for help after looking around.",
    skills: ["Welcoming", "Asking questions", "Recommending", "Explaining"],
    complication: "The customer says they are only looking, then returns with a vague question about gifts.",
    conditions: ["Welcome the customer politely.", "Offer help in a low-pressure way.", "Ask one useful question when the customer is ready.", "Point to a suitable area or next step."],
    openingLine: "Good afternoon. I am just looking around for now.",
    steps: ["Greet the customer.", "Respect their wish to browse.", "Offer a simple way to ask for help.", "Respond when they return with a gift question."],
    vocabulary: ["browse", "gift", "looking for", "section", "help", "customer"],
    targetExpressions: ["Welcome. Please take your time.", "How can I help you today?", "Are you looking for anything in particular?", "I can show you where those are.", "Please let me know if you have any questions."],
    durationSeconds: 180,
    difficulty: "easy"
  },
  {
    id: "retail-find-needs",
    title: "Finding Out What a Customer Needs",
    category: "Retail & Customer Service",
    categoryId: "retail-customer-service",
    scenario: "A customer wants a travel bag but gives only a general description. The employee asks focused questions about use, size and budget before suggesting products.",
    aiRole: "Customer searching for a product",
    studentRole: "Retail sales associate",
    goal: "Discover the customer's intended use, size, features and budget, then summarize the need before showing an appropriate option.",
    aiContext: "The customer needs a carry-on bag for a three-day business trip, wants a laptop compartment and prefers to stay near ¥20,000. Reveal the details as the employee asks.",
    skills: ["Asking questions", "Clarifying", "Recommending", "Confirming information"],
    complication: "The customer wants a large bag that is still acceptable as carry-on luggage, so the employee should clarify the actual size requirement.",
    conditions: ["Ask about the purpose and length of use.", "Ask about size, feature and budget priorities.", "Summarize what the customer needs.", "Suggest a suitable product direction without overpromising airline rules."],
    openingLine: "I need a bag for a short business trip, but I am not sure which one would work.",
    steps: ["Ask how the product will be used.", "Clarify size and feature priorities.", "Ask about budget.", "Summarize and suggest an appropriate product."],
    vocabulary: ["carry-on", "business trip", "laptop compartment", "budget", "size", "feature"],
    targetExpressions: ["What will you mainly use it for?", "What size would work best?", "Which feature is most important?", "Let me make sure I understand.", "This option may suit your needs."],
    durationSeconds: 240,
    difficulty: "easy"
  },
  {
    id: "retail-explain-features",
    title: "Explaining Product Features",
    category: "Retail & Customer Service",
    categoryId: "retail-customer-service",
    scenario: "A customer is comparing a compact noise-cancelling headset on the display and asks how it works, how it connects and what is included.",
    aiRole: "Customer evaluating a product",
    studentRole: "Retail product specialist",
    goal: "Explain the supplied product features in plain English, connect features to the customer's need and identify any specification that must be checked.",
    aiContext: "The headset has wireless connection, a carrying case and a microphone. Battery life and the exact warranty period are not supplied. The customer wants it for train travel and work calls.",
    skills: ["Explaining features", "Asking questions", "Sharing information", "Confirming information"],
    complication: "The customer asks for the exact battery life and warranty terms, which are not on the supplied display card.",
    conditions: ["Ask how the customer plans to use the product.", "Explain at least three supplied features.", "Connect a feature to train or call use.", "Offer to check the battery or warranty detail instead of guessing."],
    openingLine: "Could you explain what this headset can do? I would use it on trains and for work calls.",
    steps: ["Ask about the customer's use.", "Explain connection, case and microphone.", "Relate a feature to the customer's priorities.", "Handle the unknown specification with a check."],
    vocabulary: ["wireless", "noise cancelling", "microphone", "carrying case", "battery life", "warranty"],
    targetExpressions: ["This model has…", "It would be useful for…", "The microphone is included.", "Let me check the exact specification.", "I'll confirm the warranty information."],
    durationSeconds: 240
  },
  {
    id: "retail-compare-products",
    title: "Comparing Two Products",
    category: "Retail & Customer Service",
    categoryId: "retail-customer-service",
    scenario: "A customer is choosing between two carry-on bags. The employee compares size, weight, material and price without pushing a product that does not fit the customer's use.",
    aiRole: "Customer comparing two products",
    studentRole: "Retail associate",
    goal: "Ask what matters most, compare the supplied features clearly, explain a trade-off and help the customer choose or identify what to check next.",
    aiContext: "Bag A is lighter and ¥18,000. Bag B has stronger material and more pockets but is ¥24,000. Exact airline size rules are not supplied.",
    skills: ["Comparing", "Asking questions", "Explaining features", "Recommending"],
    complication: "The customer wants the stronger bag but is worried about weight and airline restrictions.",
    conditions: ["Ask which priorities matter most.", "Compare at least two supplied features.", "Explain one trade-off fairly.", "Avoid guaranteeing airline acceptance without checking.", "Support a decision or clear next step."],
    openingLine: "These two bags look similar. Which one would you recommend for regular business travel?",
    steps: ["Ask about weight, durability and price priorities.", "Compare the two products.", "Explain the main trade-off.", "Check the size question or recommend how to verify it."],
    vocabulary: ["compare", "lighter", "durable", "pockets", "trade-off", "price"],
    targetExpressions: ["The main difference is…", "This one is lighter, while that one…", "Which feature matters most to you?", "I don't want to guarantee that without checking.", "Based on your priorities, I would suggest…"],
    durationSeconds: 240
  },
  {
    id: "retail-check-stock",
    title: "Checking Size, Colour or Stock",
    category: "Retail & Customer Service",
    categoryId: "retail-customer-service",
    scenario: "A customer wants a particular jacket in medium and navy, but the display only has a different size and color. The employee checks the actual stock and explains alternatives.",
    aiRole: "Customer looking for a specific item",
    studentRole: "Retail store employee",
    goal: "Confirm the requested product, size and color, check stock rather than guessing, and offer an available alternative or next step.",
    aiContext: "The customer wants the Horizon jacket, medium, navy. The floor sample is small and black. The employee must check the stock system or back room; availability is not supplied.",
    skills: ["Clarifying", "Confirming information", "Recommending", "Problem solving"],
    complication: "The customer is leaving soon and asks whether the item can be reserved or transferred, but the store policy is not supplied.",
    conditions: ["Confirm the product, size and color.", "Check stock instead of assuming.", "Report the result accurately or offer to check it.", "Suggest an alternative if needed.", "Avoid inventing reservation or transfer policy."],
    openingLine: "Do you have this Horizon jacket in medium and navy?",
    steps: ["Repeat the product details.", "Check the stock information.", "Explain the result clearly.", "Offer an alternative or check the policy for reservation or transfer."],
    vocabulary: ["size", "colour", "stock", "back room", "reserve", "transfer"],
    targetExpressions: ["Let me check the stock for you.", "May I confirm the size and colour?", "We have one available in…", "I need to check whether we can reserve it.", "Would you like to see another colour?"],
    durationSeconds: 240
  },
  {
    id: "retail-return-exchange",
    title: "Handling a Return or Exchange",
    category: "Retail & Customer Service",
    categoryId: "retail-customer-service",
    scenario: "A customer returns with a shirt that does not fit and asks for an exchange. The employee gathers the receipt and product details and checks the store policy.",
    aiRole: "Customer requesting an exchange",
    studentRole: "Retail customer-service employee",
    goal: "Listen to the request, confirm the purchase and item condition, ask for the receipt, explain that the return policy must be checked and outline the next step without inventing a decision.",
    aiContext: "The customer bought the shirt three days ago and has a receipt. The tags are still attached. The exact exchange period and condition policy are not supplied.",
    skills: ["Listening", "Clarifying", "Confirming information", "Handling concerns"],
    complication: "The customer asks for a refund if an exchange is not possible, but the store policy is not available to the employee.",
    conditions: ["Acknowledge the customer's request.", "Confirm purchase date, receipt and item condition.", "Ask which size or color they want.", "Check the return or exchange policy.", "Explain the next step without promising the outcome."],
    openingLine: "I bought this shirt a few days ago, but it does not fit. Could I exchange it?",
    steps: ["Listen and clarify the requested solution.", "Confirm the receipt and item details.", "Ask what replacement the customer wants.", "Check the policy and explain what can happen next."],
    vocabulary: ["return", "exchange", "receipt", "tags", "condition", "policy"],
    targetExpressions: ["I understand you would like an exchange.", "May I see the receipt?", "Is the item unused and are the tags attached?", "Let me check our return policy.", "I'll confirm what options are available."],
    durationSeconds: 300,
    difficulty: "challenge"
  },
  {
    id: "retail-product-problem",
    title: "Helping with a Product Problem",
    category: "Retail & Customer Service",
    categoryId: "retail-customer-service",
    scenario: "A customer returns with a portable charger that stopped working after a short time. The employee asks what happened, checks the purchase information and explains the support path.",
    aiRole: "Customer reporting a product problem",
    studentRole: "Retail customer-service employee",
    goal: "Understand the problem, ask useful troubleshooting questions, confirm receipt or warranty information and offer a realistic check or support next step.",
    aiContext: "The charger was purchased last month, the customer has a receipt, and it no longer charges a phone. The exact warranty process and replacement decision are not supplied.",
    skills: ["Asking questions", "Problem solving", "Clarifying", "Handling concerns"],
    complication: "The customer wants an immediate replacement, but the employee must follow the supplied process and not promise an outcome.",
    conditions: ["Let the customer describe the problem.", "Ask when and how it stopped working.", "Confirm the receipt and product details.", "Explain the known support or inspection step.", "Avoid promising a replacement before checking."],
    openingLine: "This charger stopped working after only a few weeks. Can you replace it today?",
    steps: ["Listen and summarize the issue.", "Ask one or two useful troubleshooting questions.", "Confirm the receipt and purchase date.", "Check the policy or support process and explain the next step."],
    vocabulary: ["portable charger", "charge", "receipt", "warranty", "replace", "inspection"],
    targetExpressions: ["I'm sorry you are having this problem.", "When did it stop working?", "Let me confirm the purchase details.", "I'll check the warranty process.", "I can't promise a replacement until we check it.", "Here is the next step."],
    durationSeconds: 300
  },
  {
    id: "retail-complete-sale",
    title: "Completing the Sale",
    category: "Retail & Customer Service",
    categoryId: "retail-customer-service",
    scenario: "A customer has chosen a camera accessory and is ready to pay. The employee confirms the item, explains the supplied basic warranty information and completes the interaction.",
    aiRole: "Customer ready to purchase",
    studentRole: "Retail sales associate",
    goal: "Confirm the chosen product and quantity, answer a basic price or warranty question using supplied information, take payment and provide the receipt or next step.",
    aiContext: "The customer has selected one compact tripod priced at ¥8,800. A one-year manufacturer warranty is stated on the product card. The customer asks whether the store has an extended warranty; that option is not supplied.",
    skills: ["Confirming information", "Explaining features", "Taking orders", "Welcoming"],
    complication: "The customer asks about an extended warranty that may or may not be available.",
    conditions: ["Confirm the product, quantity and price.", "Explain the supplied warranty accurately.", "Check the extended-warranty question instead of guessing.", "Confirm payment and receipt details.", "Close the sale politely."],
    openingLine: "I will take this tripod, please. How much is it, and what happens if it breaks?",
    steps: ["Confirm the item and quantity.", "Explain price and supplied warranty.", "Offer to check the extra warranty question.", "Complete payment and say goodbye."],
    vocabulary: ["tripod", "quantity", "price", "warranty", "receipt", "payment"],
    targetExpressions: ["Let me confirm your selection.", "The price is…", "The product card says it has…", "I'll check whether an extended warranty is available.", "Here is your receipt.", "Thank you for shopping with us."],
    durationSeconds: 240
  }
];

export const RETAIL_CUSTOMER_SERVICE_LIBRARY = seeds.map(workplace);

