import { workplace, type WorkplaceSeed } from "./speakingWorkplaceBuilder.js";

const seeds: WorkplaceSeed[] = [
  {
    id: "luxury-car-welcome-customer",
    title: "Welcoming a Customer to the Dealership",
    category: "Luxury Car Sales",
    categoryId: "luxury-car-sales",
    scenario: "A first-time overseas customer visits a premium used-car dealership. They are interested in a Mercedes-Benz but are not sure which model fits their life.",
    aiRole: "Customer visiting the dealership",
    studentRole: "Luxury-car sales consultant",
    goal: "Welcome the customer, discover how they will use the car, understand sedan or SUV preferences, respond to a maintenance-cost concern, and suggest suitable options.",
    aiContext: "The customer is friendly but undecided. They commute in the city, sometimes travel with family, and worry that a premium car may be expensive to maintain. Reveal needs gradually when the consultant asks useful questions.",
    skills: ["Welcoming", "Asking questions", "Recommending", "Clarifying"],
    complication: "After the first recommendation, the customer asks whether maintenance will be difficult or expensive in Japan.",
    conditions: ["Greet the customer professionally.", "Ask about use, passengers and priorities.", "Clarify whether a sedan or SUV is a better fit.", "Acknowledge the maintenance concern and suggest a sensible next step."],
    openingLine: "Good afternoon. I am looking for a Mercedes-Benz, but I am not sure which model would suit me.",
    steps: ["Welcome the visitor and offer help.", "Ask how they will mainly use the car.", "Ask about body style, passengers and priorities.", "Suggest two suitable directions and invite the customer to look at options."],
    vocabulary: ["commute", "family", "sedan", "SUV", "maintenance", "option"],
    targetExpressions: ["Welcome. How can I help you today?", "What kind of car are you looking for?", "How will you mainly use the car?", "What's most important to you?", "Would you prefer a sedan or an SUV?", "Let me show you a few options."],
    durationSeconds: 240,
    difficulty: "easy"
  },
  {
    id: "luxury-car-explain-vehicle",
    title: "Explaining a Mercedes to a Customer",
    category: "Luxury Car Sales",
    categoryId: "luxury-car-sales",
    scenario: "A customer is inspecting a fictional training vehicle, a 2023 Mercedes-Benz E 200 AMG Line, and wants accurate information before deciding whether to continue.",
    aiRole: "Customer inspecting a vehicle",
    studentRole: "Dealership sales consultant",
    goal: "Explain the supplied vehicle details accurately, answer questions about mileage, condition, history and safety, and identify information that must be checked.",
    aiContext: "Use only this training vehicle sheet: 18,500 km; white; black leather; one previous owner; dealer service history; no recorded accident history; panoramic sunroof; 360-degree camera; adaptive cruise control; heated front seats; ¥7,480,000; 12-month dealer warranty. The answer to the brake-pad replacement question is not supplied.",
    skills: ["Explaining", "Sharing information", "Clarifying", "Confirming information"],
    complication: "The customer asks, 'When were the brake pads last replaced?' The consultant must not guess and should offer to check.",
    conditions: ["Give accurate mileage, ownership and condition information.", "Explain at least two equipment or safety features.", "Answer the price and warranty questions using the supplied sheet.", "Say that the brake-pad date needs to be checked instead of inventing it."],
    openingLine: "Could you tell me more about this 2023 E 200? I want to understand its history before I decide.",
    steps: ["Confirm which vehicle the customer means.", "Explain mileage, ownership and service history.", "Describe useful equipment and warranty information.", "Handle the unavailable brake-pad detail professionally and offer the next check."],
    vocabulary: ["mileage", "previous owner", "service history", "accident history", "warranty", "brake pads"],
    targetExpressions: ["This vehicle has…", "It has one previous owner.", "The service history is…", "There is no recorded accident history.", "Let me check that for you.", "I'll confirm that information."],
    durationSeconds: 300,
    referenceItems: [
      { label: "Vehicle", detail: "2023 Mercedes-Benz E 200 AMG Line" },
      { label: "Mileage", detail: "18,500 km" },
      { label: "Condition", detail: "White exterior · black leather" },
      { label: "History", detail: "One previous owner · dealer service history · no recorded accident history" },
      { label: "Features", detail: "Panoramic sunroof · 360-degree camera · adaptive cruise control · heated front seats" },
      { label: "Price", detail: "¥7,480,000" },
      { label: "Warranty", detail: "12-month dealer warranty" }
    ]
  },
  {
    id: "luxury-car-find-right-car",
    title: "Finding the Right Car for a Customer",
    category: "Luxury Car Sales",
    categoryId: "luxury-car-sales",
    scenario: "A family customer wants a premium used car, but the consultant must discover the priorities before recommending a vehicle.",
    aiRole: "Customer shopping for a family car",
    studentRole: "Sales consultant",
    goal: "Ask focused questions to uncover budget, family use, driving pattern, luggage needs, seating height, mileage and preferred colors, then make a justified recommendation.",
    aiContext: "Do not volunteer the full profile at once. Reveal these answers when asked: budget around ¥8,000,000; family of three; mostly city driving; occasional skiing; good luggage space; higher driving position; under 40,000 km; black, white or silver preferred.",
    skills: ["Asking questions", "Clarifying", "Recommending", "Giving reasons"],
    complication: "The customer likes a car with the right seating position but asks whether it will still handle luggage for a ski trip.",
    conditions: ["Ask about budget and passengers.", "Ask how and where the car will be driven.", "Check luggage, seating height, mileage and color preferences.", "Recommend a suitable direction and explain why it fits."],
    openingLine: "I need a premium car for my family, but I am not sure where to start.",
    steps: ["Ask about budget and family use.", "Explore normal driving and occasional trips.", "Clarify practical preferences and vehicle history limits.", "Recommend one or two options with reasons."],
    vocabulary: ["budget", "family", "luggage space", "driving position", "city driving", "mileage"],
    targetExpressions: ["What is your budget range?", "How many people usually travel with you?", "What kind of driving do you do most?", "Would luggage space be important?", "Based on what you've told me…", "This option could be a good fit because…"],
    durationSeconds: 300
  },
  {
    id: "luxury-car-test-drive",
    title: "Arranging and Discussing a Test Drive",
    category: "Luxury Car Sales",
    categoryId: "luxury-car-sales",
    scenario: "A customer has shortlisted a premium vehicle and wants to experience it before making a decision. The consultant must organize a clear, safe test-drive conversation.",
    aiRole: "Customer considering a test drive",
    studentRole: "Dealership sales consultant",
    goal: "Offer and arrange a test drive, ask for basic booking information, explain the process without inventing policy, answer questions, and agree on a next step after the drive.",
    aiContext: "The customer has a busy afternoon and asks how long the drive will take, what they should bring, and whether a family member can join. The dealership's exact document policy is not supplied.",
    skills: ["Welcoming", "Asking questions", "Explaining", "Confirming information"],
    complication: "The customer asks for a specific document requirement that the consultant does not know. A professional answer is to check rather than make a promise.",
    conditions: ["Offer a suitable test-drive time.", "Confirm the customer name and preferred vehicle.", "Explain the known process and timing clearly.", "Handle one unknown policy detail by offering to confirm it.", "Ask for impressions and suggest a follow-up step."],
    openingLine: "The car looks promising. Could I take it for a short drive this afternoon?",
    steps: ["Ask which vehicle and time the customer prefers.", "Confirm basic booking details.", "Explain the available process and expected duration.", "Answer known questions, check unknown requirements, and follow up after the drive."],
    vocabulary: ["test drive", "appointment", "available", "confirm", "route", "impression"],
    targetExpressions: ["Would you like to arrange a test drive?", "What time would be convenient?", "Let me confirm the details.", "I'll check that requirement for you.", "What did you think of the drive?", "Would you like to compare another option?"],
    durationSeconds: 240
  },
  {
    id: "luxury-car-discuss-price",
    title: "Discussing Price with a Customer",
    category: "Luxury Car Sales",
    categoryId: "luxury-car-sales",
    scenario: "A customer likes the fictional 2023 Mercedes-Benz E 200 AMG Line, listed at ¥7,480,000, but says the price is higher than expected and later asks for ¥7,000,000 today.",
    aiRole: "Customer negotiating over a vehicle",
    studentRole: "Sales consultant",
    goal: "Understand the customer's budget, explain the value included in the listed price, avoid unauthorized promises, and propose an appropriate next step such as manager approval or an alternative vehicle.",
    aiContext: "The customer first says the car costs more than planned, then says, 'If you can do ¥7 million, I'll buy it today.' No discount authority is supplied. The consultant may prepare an estimate or compare alternatives.",
    skills: ["Asking questions", "Negotiating", "Explaining", "Confirming information"],
    complication: "The customer presses for an immediate yes and treats silence as agreement. The consultant must explain that approval is needed.",
    conditions: ["Ask about the customer's budget and priorities.", "Explain relevant included value without exaggerating.", "Do not accept an unauthorized price.", "Offer manager approval, an estimate or a suitable alternative.", "Confirm the next step clearly."],
    openingLine: "The E 200 is attractive, but ¥7.48 million is more than I wanted to spend.",
    steps: ["Acknowledge the price concern.", "Ask what budget or feature matters most.", "Explain the supplied vehicle value and available options.", "Respond to the ¥7 million offer with a realistic approval step."],
    vocabulary: ["listed price", "budget", "value", "approval", "estimate", "alternative"],
    targetExpressions: ["I understand your concern about the price.", "May I ask about your budget?", "The price includes…", "I need to check with my manager.", "Let me prepare an estimate.", "Would you like to compare another option?"],
    durationSeconds: 300
  },
  {
    id: "luxury-car-trade-in",
    title: "Discussing a Customer's Trade-In",
    category: "Luxury Car Sales",
    categoryId: "luxury-car-sales",
    scenario: "A customer wants to trade in a 2020 Toyota Harrier while buying a premium vehicle. The consultant needs enough information for a preliminary conversation without promising a valuation.",
    aiRole: "Customer offering a trade-in",
    studentRole: "Dealership trade-in consultant",
    goal: "Ask about the trade-in's model, mileage, condition, service history, accident history, finance and documents, then explain that an inspection is needed before valuation.",
    aiContext: "The vehicle is a 2020 Toyota Harrier, 62,000 km, pearl white, one owner, regularly serviced, with minor rear-bumper scratches. The owner reports no major accident history, but there may be outstanding finance. Ask questions rather than assuming the details are complete.",
    skills: ["Asking questions", "Clarifying", "Explaining", "Confirming information"],
    complication: "The customer wants a trade-in figure immediately, but the condition and possible finance need to be checked first.",
    conditions: ["Confirm the vehicle year, model and mileage.", "Ask about condition, service and accident history.", "Ask about finance, keys and documents.", "Explain the inspection and valuation next step without giving a made-up figure."],
    openingLine: "I may trade in my 2020 Toyota Harrier. Can you tell me what it might be worth?",
    steps: ["Identify the vehicle and basic history.", "Ask about visible condition and servicing.", "Clarify finance, keys and documents.", "Explain what the inspection will establish and what happens next."],
    vocabulary: ["trade-in", "mileage", "inspection", "valuation", "outstanding finance", "documents"],
    targetExpressions: ["Could I ask a few questions about the car?", "Has it been regularly serviced?", "Is there any finance remaining?", "We need to inspect the vehicle before valuation.", "I can't give a firm figure yet.", "I'll explain the next step."],
    durationSeconds: 300,
    referenceItems: [
      { label: "Vehicle", detail: "2020 Toyota Harrier · pearl white" },
      { label: "Mileage", detail: "62,000 km" },
      { label: "Condition", detail: "Minor rear-bumper scratches" },
      { label: "History", detail: "One owner · regularly serviced · no major accident history according to owner" },
      { label: "Check", detail: "Possible outstanding finance · confirm keys and documents" }
    ]
  },
  {
    id: "luxury-car-buy-used-car",
    title: "Buying a Used Car for the Dealership",
    category: "Luxury Car Sales",
    categoryId: "luxury-car-sales",
    scenario: "A seller brings a 2021 Mercedes-Benz GLC 300 to a dealership and wants an immediate purchase price. The employee must gather facts and set a realistic process.",
    aiRole: "Vehicle owner hoping to sell today",
    studentRole: "Dealership used-car buyer",
    goal: "Ask about the vehicle, confirm history and paperwork, acknowledge the seller's target, and explain why a firm offer requires inspection before approval.",
    aiContext: "The vehicle is a 2021 Mercedes-Benz GLC 300, 35,000 km, black, with minor wheel scratches, dealer service history, two keys and current finance. The seller wants ¥6,000,000 and repeatedly asks for an immediate answer.",
    skills: ["Asking questions", "Clarifying", "Negotiating", "Confirming information"],
    complication: "The seller says another buyer will decide quickly and asks the employee to promise ¥6,000,000 before inspection.",
    conditions: ["Confirm the vehicle details and service history.", "Ask about visible damage, keys and finance.", "Acknowledge the requested price without promising it.", "Explain the inspection and approval process.", "Agree on a practical next step."],
    openingLine: "I want to sell my GLC 300 today. Can you offer me ¥6 million right now?",
    steps: ["Ask for the basic vehicle and ownership information.", "Clarify condition, keys and finance.", "Respond to the price request professionally.", "Explain inspection, approval and the earliest realistic follow-up."],
    vocabulary: ["seller", "purchase price", "firm offer", "inspection", "finance", "approval"],
    targetExpressions: ["Let me confirm the vehicle details.", "I understand you need a quick answer.", "The firm offer depends on an inspection.", "I need to check with my manager.", "We can prepare a preliminary review.", "When would you be available for the inspection?"],
    durationSeconds: 300,
    referenceItems: [
      { label: "Vehicle", detail: "2021 Mercedes-Benz GLC 300 · black" },
      { label: "Mileage", detail: "35,000 km" },
      { label: "Condition", detail: "Minor wheel scratches" },
      { label: "History", detail: "Dealer service history · two keys" },
      { label: "Finance", detail: "Currently financed" },
      { label: "Seller request", detail: "¥6,000,000" }
    ]
  },
  {
    id: "luxury-car-close-sale",
    title: "Closing a Luxury Car Sale",
    category: "Luxury Car Sales",
    categoryId: "luxury-car-sales",
    scenario: "A customer has decided to buy a premium vehicle. The consultant must guide the customer through the dealership's known next steps without inventing legal or document requirements.",
    aiRole: "Customer ready to purchase",
    studentRole: "Sales consultant completing the sale",
    goal: "Explain the deposit, paperwork review, financing discussion, document confirmation and expected delivery timing, while flagging unknown requirements for confirmation.",
    aiContext: "The customer is positive but asks practical questions: how much is the deposit, which documents are needed, whether financing is available, and when delivery will happen. Exact deposit amount, legal requirements and delivery date are not supplied.",
    skills: ["Explaining", "Confirming information", "Asking questions", "Scheduling"],
    complication: "The customer asks about a document or legal requirement the consultant cannot verify from the supplied information.",
    conditions: ["Confirm the vehicle and the customer's decision.", "Explain the known stages in a clear order.", "Do not invent an amount, legal rule or delivery date.", "Use a professional check-and-confirm response.", "Summarize the next step and follow-up."],
    openingLine: "I would like to go ahead with the purchase. What happens next?",
    steps: ["Congratulate the customer and confirm the vehicle.", "Outline deposit and paperwork as steps to complete.", "Discuss financing as an option without promising approval.", "Confirm what is known, check unknown details and explain follow-up."],
    vocabulary: ["deposit", "paperwork", "financing", "delivery", "confirm", "approval"],
    targetExpressions: ["Let's confirm the vehicle details.", "The next step is to review the paperwork.", "We can discuss financing options.", "I'll confirm that with you.", "I'll check the delivery timing.", "I'll confirm that for you."],
    durationSeconds: 300
  },
  {
    id: "luxury-car-handle-concern",
    title: "Handling a Concerned Luxury-Car Customer",
    category: "Luxury Car Sales",
    categoryId: "luxury-car-sales",
    scenario: "A customer is close to choosing a premium used car but raises several concerns about price, maintenance, warranty, ownership history, accident records, competitors and resale value.",
    aiRole: "Cautious customer comparing premium brands",
    studentRole: "Experienced luxury-car consultant",
    goal: "Listen carefully, identify the most important concern, answer only with supported information, avoid attacking competitors or pressuring the customer, and agree on evidence or a next step.",
    aiContext: "The customer may ask about purchase price, maintenance cost, warranty, previous ownership, accident history, BMW, Audi, Lexus or resale value. No unsupported market guarantee is available. The customer responds well to calm questions and concrete checks.",
    skills: ["Listening", "Handling concerns", "Clarifying", "Negotiating"],
    complication: "The customer changes from one concern to another and asks for a resale-value guarantee. The consultant should acknowledge uncertainty and offer to provide or check relevant evidence.",
    conditions: ["Listen and acknowledge the customer's concern.", "Ask which issue matters most to the decision.", "Give accurate information and distinguish known facts from checks.", "Avoid negative claims about competitors or guarantees.", "Offer evidence or a clear, low-pressure next step."],
    openingLine: "I like the car, but I still have several concerns before I can make a decision.",
    steps: ["Invite the customer to explain the concerns.", "Summarize and prioritize the main issue.", "Answer with supplied facts or offer to check.", "Compare options fairly and agree on evidence, a second visit or time to decide."],
    vocabulary: ["concern", "maintenance cost", "warranty", "ownership history", "resale value", "evidence"],
    targetExpressions: ["I understand your concern.", "Which point is most important to you?", "Here is what I can confirm.", "I don't want to guess about that.", "We can compare the information fairly.", "Would it help if I checked that and followed up?"],
    durationSeconds: 300,
    difficulty: "challenge"
  }
];

export const LUXURY_CAR_SALES_LIBRARY = seeds.map(workplace);
